### ISSUE TITLE
🚧 | Y4: Alternative Filecoin consensus

### ISSUE THREAD

**Issue by jsoares** [consensus-shipyard/consensuslab#10]
## Description
Design and make a roadmap for the replacement of the top-level consensus of Filecoin.

## Scope
This project covers the short-to-midterm improvements to Filecoin consensus, both fixing low-hanging-fruit type of problems with patches and more fundamentally changing the consensus protocol to improve security and attain new performance goals.

## Roadmap
eta: 2023-12-31
children: 
* #192

#### 2022-10-27, Unexpected Consensus? The Possible Futures of the Filecoin Network
[![Watch the video](https://img.youtube.com/vi/2ARFlCL4QFY/hqdefault.jpg)](https://youtu.be/2ARFlCL4QFY)

#### 2023-04-03, Scalable Asynchronous Randomized Byzantine Agreement
[![Watch the video](https://img.youtube.com/vi/ktdc22teZxs/hqdefault.jpg)](https://youtu.be/ktdc22teZxs)

## Resources
* https://github.com/consensus-shipyard/ecpp

**Comment by sa8** [comment]
List of related resources:

- [Reading list](https://github.com/protocol/ConsensusLab/discussions/104) with link to each summaries.
- [Literature review takeaway](https://github.com/protocol/ConsensusLab/discussions/117)
- Draft of [threat model](https://www.overleaf.com/read/grnswdbpkwck)
- [Proposal ](https://github.com/protocol/ConsensusLab/discussions/116) to look at combining EC with Snowman.
  - [Icicle](https://www.overleaf.com/read/grnswdbpkwck) draft
